/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *   Do not change the name of the hook
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import useBannerTopResponsiveSize from './useBannerTopResponsiveSize';
import { useAuthContext } from '@asgardeo/auth-react';

/* These are the possible values for the current variant. Use this to change the currentVariant dynamically.
Please don't modify */
const variantOptions = {
  Property1Desktop: 'Property1Desktop',
  Property1Mobile: 'Property1Mobile',
};

const useBannerTop = () => {
  const [currentVariant, setCurrentVariant] = React.useState<string>(
    variantOptions['Property1Desktop']
  );

  const { signOut, state } = useAuthContext();

  const breakpointsVariant = useBannerTopResponsiveSize();

  React.useEffect(() => {
    if (breakpointsVariant !== currentVariant) {
      setCurrentVariant(breakpointsVariant);
    }
  }, [breakpointsVariant]);

  

  React.useEffect(() => {
    if (breakpointsVariant !== currentVariant) {
      setCurrentVariant(breakpointsVariant);
    }
  }, [breakpointsVariant]);

  const handleSignOut = () => {
    signOut();
  }

  const data: any = { currentVariant, state };

  const fns: any = { setCurrentVariant, handleSignOut };

  return { data, fns };
};

export default useBannerTop;
