pr: none
trigger:
  batch: true
  branches:
    include:
      - main

variables:
  - group: choreo-samples

steps:
  - task: AzureCLI@2
    displayName: Upload files to Azure Storage Account
    inputs:
      azureSubscription: $(resource_group)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        mapfile -t icons < <(find -- * -maxdepth 1 -name "icon.png")
        
        echo "[INFO] creating temporary directory for icons"
        mkdir -p "choreo-samples"
        for icon in "${icons[@]}"; do
          directory=$(dirname "$icon")
          mkdir -p "choreo-samples/$directory"
          echo "[INFO] copying $icon to choreo-samples/$directory"
          cp "$icon" "choreo-samples/$directory"
        done
        
        echo "[INFO] copying index.json to choreo-samples/"
        cp index.json choreo-samples/
        
        echo "[INFO] uploading files to Azure Storage Account"
        az storage blob upload-batch \
          --account-name "$(storage_account_name)" \
          -s "choreo-samples/" \
          -d "choreo-samples" \
          --overwrite true
        
        echo "[INFO] purging CDN endpoint"
        az cdn endpoint purge \
          --content-paths '/*'\
          --profile-name "$(cdn_profile)" \
          --name "$(cdn_endpoint)" \
          --resource-group "$(resource_group)"
