resources:
  repositories:
    - repository: common-templates
      type: github
      name: wso2-enterprise/choreo-common-pipeline-templates
      endpoint: wso2-enterprise

pr: none
trigger:
  batch: true
  branches:
    include:
      - main

variables:
  - group: choreo-samples

steps:
  - task: Docker@2
    displayName: 'Login to choreoanonymouspullable.azurecr.io'
    inputs:
      command: login
      containerRegistry: $(container_registry)

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install pyyaml
      pip install requests
    displayName: 'Install dependencies'

  - script: python .azure/scripts/process_metadata.py 
    displayName: 'Run metadata extraction script'

  - script: |
      echo "Giving execute permission to trivy-scan.sh"
      chmod +x .azure/scripts/trivy-scan.sh
    displayName: "Set execute permissions"

  - template: install/install-trivy.yaml@common-templates
  - script: |
        echo "##[group]Running Trivy scan for each image"

        exit_code=0

        while read -r image; do
          echo "Scanning image: $image"
          .azure/scripts/trivy-scan.sh "$image"

          scan_exit_code=$?

          if [ $scan_exit_code -ne 0 ]; then
            echo "Trivy scan failed for image: $image"
            exit_code=1  # Mark exit_code as failure
          fi
        done < image_urls.txt

        echo "##[endgroup]"

        exit $exit_code
    displayName: "Run Trivy scan for quick deployable images"

  - script: |
        echo "##[group]Pushing images to ACR"
        while read -r image; do
          echo "Pushing image: $image"
          docker push "$image"
        done < image_urls.txt
        echo "##[endgroup]"
    displayName: 'Push Quick Deployable Docker Images'

  - task: AzureCLI@2
    displayName: Upload files to Azure Storage Account
    inputs:
      azureSubscription: $(resource_group)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "[INFO] staging directory"
        tree $(Build.StagingDirectory)
        echo "===================================="
        echo

        echo "[INFO] uploading files to Azure Storage Account"
        az storage blob upload-batch \
          --account-name "$(storage_account_name)" \
          -s "$(Build.StagingDirectory)" \
          -d "choreo-samples" \
          --overwrite true
        
        echo "[INFO] purging CDN endpoint"
        az cdn endpoint purge \
          --content-paths '/*'\
          --profile-name "$(cdn_profile)" \
          --name "$(cdn_endpoint)" \
          --resource-group "$(resource_group)"
  
  - task: AzureCLI@2
    displayName: Download version file from Azure Storage Account and set variable
    inputs:
      azureSubscription: $(resource_group)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "[INFO] downloading version file from Azure Storage Account"
        az storage blob download \
          --account-name "$(storage_account_name)" \
          -c "choreo-samples" \
          -n "choreo-samples-version.txt" \
          -f "$(Build.ArtifactStagingDirectory)/choreo-samples-version.txt" \
          --overwrite true
        echo "[INFO] reading samples version from of the version file"
        SAMPLES_VERSION=$(< "$(Build.ArtifactStagingDirectory)/choreo-samples-version.txt")
        echo "##vso[task.setvariable variable=SAMPLES_VERSION]$SAMPLES_VERSION"     

  - template: update-image-in-cp-overlays.yml@common-templates
    parameters:
      CONFIGS:
        - CHOREO_SAMPLES_VERSION='$(SAMPLES_VERSION)'
