resources:
  repositories:
    - repository: common-templates
      type: github
      name: wso2-enterprise/choreo-common-pipeline-templates
      endpoint: wso2-enterprise
      
trigger: none

pr:
  branches:
    include:
      - 'main'

variables:
  - group: choreo-samples

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.x"
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install pyyaml
    displayName: "Install dependencies"

  - script: |
      python .azure/scripts/validate_samples.py
    displayName: "Metadata Validation"

  - script: |
      IMAGE_URLS=$(cat ./image_urls.txt)
      echo "##vso[task.setvariable variable=IMAGE_URLS]\"$IMAGE_URLS\""
    displayName: "Read image_urls.txt"

  - template: install/install-trivy.yaml@common-templates
  - template: pr/trivy-scan.yaml@common-templates
    parameters:
      IMAGES: 
        - $(IMAGE_URLS)

  - script: echo 'Pull Request Validation Completed'
    displayName: "PR Validation Completed"
