resources:
  repositories:
    - repository: common-templates
      type: github
      name: wso2-enterprise/choreo-common-pipeline-templates
      endpoint: wso2-enterprise

trigger: none

pr:
  branches:
    include:
      - 'main'

variables:
  - group: choreo-samples

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.x"
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install pyyaml
    displayName: "Install dependencies"

  - script: |
      python .azure/scripts/validate_samples.py
    displayName: "Metadata Validation"

  - script: |
        echo "##[group]Set IMAGES variable"
        echo "Reading image URLs from image_urls.txt"

        # Read image URLs into a multi-line string
        IMAGES=$(cat image_urls.txt)
        echo "IMAGES variable content:"
        echo "$IMAGES"

        # Set the IMAGES variable as a multi-line string
        echo "##vso[task.setvariable variable=IMAGES]$IMAGES"
        echo "##[endgroup]"
    displayName: "Read image_urls.txt"

  - template: install/install-trivy.yaml@common-templates
  - script: |
        echo "##[group]Running Trivy scan for each image"

        # Read image_urls.txt and pass each image to trivy-scan.sh
        while IFS= read -r image; do
          echo "Scanning image: $image"
          .azure/scripts/trivy-scan.sh "$image"
        done < image_urls.txt

        echo "##[endgroup]"
    displayName: "Run Trivy scan for all images"


  - script: echo 'Pull Request Validation Completed'
    displayName: "PR Validation Completed"
