/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *   Do not change the name of the hook
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React, { useEffect } from "react";
import useQ6RewardConfirmationsResponsiveSize from "./useQ6RewardConfirmationsResponsiveSize";
import { useAuthContext } from "@asgardeo/auth-react";
import { useParams, useNavigate } from "react-router-dom";
import { Reward, RewardConfirmation } from "src/api/types";
import { getQRCode, getRewardDetails, getRewardConfirmations, getRewards } from "src/api/api";

/* These are the possible values for the current variant. Use this to change the currentVariant dynamically.
Please don't modify */
const variantOptions = {
    ScreenDesktop: "ScreenDesktop",
    ScreenMobile: "ScreenMobile",
};

const useQ6RewardConfirmations = () => {
    const [currentVariant, setCurrentVariant] = React.useState<string>(
        variantOptions["ScreenDesktop"]
    );
    const navigate = useNavigate();
    const [isRewardLoading, setIsRewardLoading] = React.useState(false);
    const [isRewardConfirmationsLoading, setIsRewardConfirmationsLoading] = React.useState(false);
    const [rewardConfirmations, setRewardConfirmations] = React.useState<RewardConfirmation[]>([]);
    const [rewardsMap, setRewardsMap] = React.useState<{ [key: string]: Reward }>({});
    const [rewards, setRewards] = React.useState<Reward[]>([]);
    const { state } = useAuthContext();

    const getRewardImage = (rewardName: string) => {
        switch (rewardName) {
            case "Target":
                return "/images/target.png";
            case "Starbucks Coffee":
                return "/images/starbucks.png";
            case "Jumba Juice":
                return "/images/jamba.png";
            case "Grubhub":
                return "/images/grubhub.png";
            default:
                return "";
        }
    };

    async function getConfirmedRewards(userId) {
        setIsRewardConfirmationsLoading(true);
        getRewardConfirmations(userId)
            .then((res) => {
                console.log('reward confirmations');
                console.log(res);
                const rewardConfirmations: RewardConfirmation[] = res.data;
                setRewardConfirmations(rewardConfirmations);
            })
            .catch((e) => {
                console.log(e);
            })
            .finally(() => {
                setIsRewardConfirmationsLoading(false);
            });
    }

    useEffect(() => {
        if (state.isAuthenticated && state.sub) {
            // TODO: Replace with below logic   
            //    getConfirmedRewards(state.sub);
            getConfirmedRewards(state.sub);
        }
    }, [state.isAuthenticated, state.sub]);

    async function getRewardDeatils() {
        setIsRewardLoading(true);
        getRewards()
            .then((res) => {
                setRewards(res.data);
                setRewardsMap(res.data.reduce((map, reward) => {
                    const logoUrl = getRewardImage(reward.name);
                    map[reward.id] = { ...reward, logoUrl };
                    return map;
                }, {}));
            })
            .catch((e) => {
                console.log(e);
            })
            .finally(() => {
                setIsRewardLoading(false);
            });
    }

    useEffect(() => {
        getRewardDeatils();
    }, []);

    const breakpointsVariant = useQ6RewardConfirmationsResponsiveSize();

    React.useEffect(() => {
        if (breakpointsVariant !== currentVariant) {
            setCurrentVariant(breakpointsVariant);
        }
    }, [breakpointsVariant]);

    const data: any = {
        currentVariant,
        isRewardLoading,
        isRewardConfirmationsLoading,
        rewardConfirmations,
        rewards,
        rewardsMap,
    };
    const backToRewards = (): any => {
        navigate("/rewards");
    };

    const fns: any = { backToRewards, setCurrentVariant };

    return { data, fns };
};

export default useQ6RewardConfirmations;
