/**********************************************************************
 *
 *   Types file generated by Quest
 *
 *   Types for the components props go in this file
 *   To set up custom types for the components props, edit the corresponding types in this file
 *   Once you edit a type to no longer by "any", be careful to not override it on your next export
 *   Verify diff before merging
 *
 *   For help and further details refer to:
 *   https://docs.quest.ai/react/fundamentals/exporting-code
 *
 *
 **********************************************************************/

export interface QrCodeProps {
  className?: any;
  imageSrc: any;
}

export interface BannerTopProps {
  className?: any;
}

export interface CardRewardProps {
  className?: any;
  reward: any;
}

export interface Footer1Props {
  className?: any;
}

export interface Q2PortalProps {
  className?: any;
}

export interface Q3RewardsProps {
  className?: any;
}

export interface Q4RewardPageProps {
  className?: any;
}

export interface Q5QrCodeProps {
  className?: any;
}

export interface Q6RewardConfirmationsProps {
  className?: any;
}
